/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadPhotoRouteImport } from './routes/upload-photo'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ReportDetailsRouteImport } from './routes/report-details'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplaintIdRouteImport } from './routes/complaint.$id'

const UploadPhotoRoute = UploadPhotoRouteImport.update({
  id: '/upload-photo',
  path: '/upload-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDetailsRoute = ReportDetailsRouteImport.update({
  id: '/report-details',
  path: '/report-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintIdRoute = ComplaintIdRouteImport.update({
  id: '/complaint/$id',
  path: '/complaint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/report-details': typeof ReportDetailsRoute
  '/success': typeof SuccessRoute
  '/track': typeof TrackRoute
  '/upload-photo': typeof UploadPhotoRoute
  '/complaint/$id': typeof ComplaintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/report-details': typeof ReportDetailsRoute
  '/success': typeof SuccessRoute
  '/track': typeof TrackRoute
  '/upload-photo': typeof UploadPhotoRoute
  '/complaint/$id': typeof ComplaintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/report-details': typeof ReportDetailsRoute
  '/success': typeof SuccessRoute
  '/track': typeof TrackRoute
  '/upload-photo': typeof UploadPhotoRoute
  '/complaint/$id': typeof ComplaintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/location'
    | '/login'
    | '/profile'
    | '/register'
    | '/report'
    | '/report-details'
    | '/success'
    | '/track'
    | '/upload-photo'
    | '/complaint/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/location'
    | '/login'
    | '/profile'
    | '/register'
    | '/report'
    | '/report-details'
    | '/success'
    | '/track'
    | '/upload-photo'
    | '/complaint/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/feedback'
    | '/help'
    | '/location'
    | '/login'
    | '/profile'
    | '/register'
    | '/report'
    | '/report-details'
    | '/success'
    | '/track'
    | '/upload-photo'
    | '/complaint/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpRoute: typeof HelpRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  ReportDetailsRoute: typeof ReportDetailsRoute
  SuccessRoute: typeof SuccessRoute
  TrackRoute: typeof TrackRoute
  UploadPhotoRoute: typeof UploadPhotoRoute
  ComplaintIdRoute: typeof ComplaintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-photo': {
      id: '/upload-photo'
      path: '/upload-photo'
      fullPath: '/upload-photo'
      preLoaderRoute: typeof UploadPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-details': {
      id: '/report-details'
      path: '/report-details'
      fullPath: '/report-details'
      preLoaderRoute: typeof ReportDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/$id': {
      id: '/complaint/$id'
      path: '/complaint/$id'
      fullPath: '/complaint/$id'
      preLoaderRoute: typeof ComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  HelpRoute: HelpRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  ReportDetailsRoute: ReportDetailsRoute,
  SuccessRoute: SuccessRoute,
  TrackRoute: TrackRoute,
  UploadPhotoRoute: UploadPhotoRoute,
  ComplaintIdRoute: ComplaintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
